name: Bug Report 🐛
about: Create a report to help us improve.
title: "[BUG] "
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How did you encounter this bug?
      placeholder: |
        1. Open the app
        2. Go to REST tab
        3. Enter URL...
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g., Chrome 114, Firefox 115
    validations:
      required: true
